config/routes.rb
Rails.application.routes.draw do
  get 'todos', to: 'todos#index'
  get 'todos/new'
  get 'todos/list'
  post 'todos', to: 'todos#create'
  get 'todos/:id', to: 'todos#show', as: 'todo'
  get 'todos/:id/edit', to: 'todos#edit', as: 'edit_todo'
  patch 'todos/:id', to: 'todos#update'
  delete 'todos/:id', to: 'todos#destroy'
  get 'todos/:id/complete', to: 'todos#complete', as: 'complete_todo'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
  validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :find_todo, only: [:show, :edit, :update, :destroy, :complete]
  def index
    @todos = Todo.all
  end
  def new
    @todo = Todo.new
  end
    def create
      @todo = Todo.new(todo_params)
      @todo.save
      redirect_to todos_path
  end
  def show
  end
  def edit
  end
  def update
    @todo.update(todo_params)
    redirect_to todos_path
  end
  def destroy
    @todo.destroy
    redirect_to todos_path
  end
  def complete
    @todo.completed= true
    @todo.save
    redirect_to todos_path
  end
  def list
    @todos = Todo.all
  end

  private
  def todo_params
    params.require(:todo).permit(:description, :completed)
  end
  def find_todo
    @todo = Todo.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Test 3</a>
    </div>
    <ul class="nav navbar-nav">
      <li><%= link_to 'Index', todos_path %></li>
      <li><%= link_to 'List',todos_list_path %></li>
      <li><%= link_to 'Formulario',todos_new_path %></li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<html>
  <head>
    <title>TodoApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://code.jquery.com/jquery-3.3.1.js" integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60=" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


  </head>

  <body>
    <%= render 'layouts/navbar' %>


    <%= yield %>
  </body>
</html>

app/views/todos/_form.html.erb
  <div class="well">
    <%= form_with model: @todo, local: true do |t| %>
      <%= t.label :description %>
      <%= t.text_field :description %>
      <%= t.label :completed %>
      <%= t.check_box :completed %>
      <%= t.submit "Enviar", class: "btn btn-success" %>
    <% end %>
  </div>

app/views/todos/_navbar.hmtl.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="<%= pages_home_path%>">Actividad 24</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <%= link_to 'Home', , class:'nav-link'%>
  <%= link_to 'Products', , class:'nav-link'%>
  <%= link_to 'About', , class:'nav-link'%>

</nav>

app/views/todos/edit.html.erb
<%= render 'todos/form' %>

app/views/todos/index.html.erb
<div class="container row">
  <div class="container col-md-7">
    <% @todos.each do |todo| %>
    <h2> Escrito Nº<%= todo.id %></h2>
    <div class="well"><%= todo.description %> <br> <%= todo.completed %></div>
    <%= link_to "Show ", todo, class: 'btn btn-primary' %>
    <%= link_to "Edit ", edit_todo_path(todo), class: 'btn btn-success' %>
    <%= link_to "Destroy ", todo, method: :delete, class: 'btn btn-danger' %>
    <%= link_to "Completed ", complete_todo_path(todo), class: 'btn btn-warning' %>
    <% end %> <br>
  </div>
  <div class="container col-md-3">
    <div class=" col-md-6">
    <%= link_to "Crear nuevo escrito ", todos_new_path, class: 'boton btn btn-info btn-lg' %>
    </div>
  </div>

</div>

app/views/todos/list.html.erb
<div class="row">
  <div class="col-md-6">
    <h1>Pendientes</h1>
    <% @todos.each do |t| %>
    <% if t.completed == false %>
    <div class="well caja row">
      <div class="col-xs-12">
        <p><%= t.description.capitalize!%></p>
      </div>
    </div>
    <% end %>
    <% end %>
  </div>

  <div class="completados col-md-6">
    <h1>Completados</h1>
    <% @todos.each do |t| %>
    <% if t.completed  %>
    <div class="well caja row">
      <div class="col-xs-12">
        <p><%= t.description.capitalize!%></p>
      </div>
    </div>
    <% end %>
    <% end %>
  </div>
 </div>

app/views/todos/new.html.erb
<%= render 'todos/form' %>

app/views/todos/show.html.erb
<h1> <%= @todo.description %></h1>
<h2> <%= @todo.completed %></h2>
<h2> <%= time_ago_in_words @todo.created_at%></h2>